#!/bin/bash

virtualenv pyrax_env
source pyrax_env/bin/activate

# Slow!
pip install -q -U -e "git+https://github.com/rackspace/pyrax@working#egg=pyrax"
# pip -q install -r requirements.txt

# pip -q install pyrax
